#!/bin/bash
#
# This script is for verifying submissions from the COMS30004 Lattice
# Boltzmann coursework. This script should be run from a directory
# containing the files that have been (or will be) submitted.
#
# This script will unload all modules apart from the defaults, and
# source 'env.sh' (if present). Finally, it will run 'make', and check
# that there is an executable with the correct name.
#

EXE=lbm
ENV=env.sh

echo

echo "Unloading all modules"
module list -t 2>.MODULES
while read MODULE
do
    module unload $MODULE 2>/dev/null
done < <(cat .MODULES | tail -n +2)

echo "Loading default modules"
module load shared default-environment
module load openmpi/gcc/64/1.6.5
module load cuda/toolkit/6.5

if [ -r $ENV ]
then
    echo "Sourcing $ENV"
    source $ENV
else
    echo "No $ENV present, skipping"
fi

echo
module list
echo

rm -f $EXE
echo "Running 'make'"
if [ ! -r Makefile ]
then
    echo
    echo "ERROR: Makefile not found."
    echo
elif ! make -B;
then
    echo
    echo "ERROR: Build failed - are you missing some extra modules from $ENV?"
    echo
elif [ ! -r $EXE ]
then
    echo
    echo "ERROR: Executable '$EXE' is not present."
    echo
else
    make clean
    echo
    echo "Submission check passed."
    echo
    echo "Please ensure that you submit all source files in the submission directory:"
    echo " - Makefile"
    echo " - lbm.c lbm.h simulation.c utils.c"
    echo " - env.sh (if used)"
    echo " - (and any other files needed to build that you've added)"
    echo
    echo "Please also submit your report, with the filename \"report.pdf\""
    echo
fi
